# CH 2 THE BASICS OF PYTHON AND R

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount("/gdrive")

#HANDS-ON ANALYSIS

---
# Use **adult_ch3_training** Dataset below.

---

#24 
Import the adult_ch3_training data set using the “Heading: Yes” setting. Rename the data set adult once it is imported.

In [ ]:
folder = "/gdrive/My Drive/Python Practice/Datasets"
adult = pd.read_csv(folder + "/adult_ch3_training")
adult[:3]

#25
Write a comment explaining the change in the data set name.

In [ ]:
print("The name of Dataset has been changed from 'adult_ch3_training' to 'adult' ")

#26
a. For Python, import the DecisionTreeClassifier command from the sklearn.tree package.<br>
b. For R, import the rpart package. Make sure you both install and open the package.

In [ ]:
from sklearn.tree import DecisionTreeClassifier #import Decision Tree Classifier

#27
Create a contingency table of workclass and sex. Save the output as table01.

In [ ]:
table01 = pd.crosstab(adult['workclass'], adult['sex'])
table01

#28
Create a contingency table of sex and marital status. Save the output as table02.

In [ ]:
table02 = pd.crosstab(adult['marital-status'], adult['sex'])
table02

#29
Display the sex and workclass values of the person in the first record.<br>
What cell of table01 do they belong to?<br>
How many other records in the data set have the same sex and workclass values?

In [ ]:
adult.loc[0, ['sex','workclass']]

In [ ]:
adult_same = adult[(adult.sex == 'Male') & (adult.workclass == 'Self-emp-not-inc')]
adult_same.shape

In [ ]:
print('This person belongs to Male and Self-emp-not-inc cell, which has 992 people.')

#30
Display the sex and marital status values of the people in records 6–10.<br>
Which cells of table02 do they belong to?<br>
How many other records in the data set have the same combinations of sex and marital status values?

In [ ]:
SixToTen = adult[['sex','marital-status']].iloc[6:11]
SixToTen

In [ ]:
print(adult[(adult['marital-status'] == 'Married-civ-spouse') & (adult.sex == 'Male')].shape)
print(adult[(adult['marital-status'] == 'Divorced') & (adult.sex == 'Male')].shape)

In [ ]:
print('The row 6 - 8, 10 belong to Male and Married-civ-spouse cell, which includes %.0f people. \nThe row 9 belongs to Male and Divorced cell, which shows %.0f.' 
      % (6010, 795))

#31
Create a new data set that has only records whose marital status is “Married‐civ‐spouse” and name the data set adultMarried.

In [ ]:
adultMarried = adult[(adult['marital-status'] == 'Married-civ-spouse')]
adultMarried[:5]

#32
Recreate the contingency table of sex and workclass using the adultMarried data set. What differences do you notice between the sexes?

In [ ]:
pd.crosstab(adultMarried['workclass'], adultMarried['sex'])

In [ ]:
table01

In [ ]:
print("The number of female decreases more than the number of male especially on 'Private' workclass")

#33
Create a new data set that has only records whose age value is greater than 40. Name the new data set adultOver40.

In [ ]:
adultOver40 = adult[(adult['age'] > 40)]
adultOver40[:5]

#34
Recreate the contingency table of sex and marital status using the adultOver40 data set. What differences do you notice?

In [ ]:
pd.crosstab(adultOver40['marital-status'], adultOver40['sex'])

In [ ]:
table02

In [ ]:
print('The number of male decreases more than the number of female especially on Never-married and Married-civ-spouse')